theme: jekyll-theme-cayman
title: ValuTime
description: Track Every Second, Know Your Worth
show_downloads: false
google_analytics:
github:
  is_project_page: true
  repository_url: https://github.com/yourusername/valutime
  owner_url: https://github.com/yourusername
  owner_name: Your Name
